import moduleImg from "@/assets/img/module.png";

interface FakeDataProps {
    id: number;
    status: string;
    date: string;
    total: number;
    price: number;
    delivery: number;
}

export let fakeData = [
    {
        id: 1,
        status: "Доставлено",
        date: "2024-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        email: "test@test.com",
        name: "Test Test",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
            {
                id: 2,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
            {
                id: 3,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
            {
                id: 4,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 2,
        status: "Оплачено",
        date: "2025-12-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 3,
        status: "Доставлено",
        date: "2025-01-03:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 4,
        status: "Оплачено",
        date: "2025-01-04:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 5,
        status: "Доставлено",
        date: "2025-01-05:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 6,
        status: "Оплачено",
        date: "2025-01-06:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 7,
        status: "Отправлен",
        date: "2025-01-07:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 8,
        status: "Черновик",
        date: "2025-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 9,
        status: "Доставлено",
        date: "2025-01-02:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 10,
        status: "Оплачено",
        date: "2025-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 11,
        status: "Отправлен",
        date: "2025-01-01:01:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 12,
        status: "Черновик",
        date: "2025-01-01:12:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        email: "test@test.com",
        name: "Test Test",
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 13,
        status: "Доставлено",
        date: "2025-01-01:23:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 14,
        status: "Оплачено",
        date: "2025-01-01:00:35",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 15,
        status: "Отправлен",
        date: "2025-01-01:00:10",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 16,
        status: "Черновик",
        date: "2025-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 33,
        status: "Доставлено",
        date: "2025-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 32,
        status: "Оплачено",
        date: "2025-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 31,
        status: "Отправлен",
        date: "2025-01-12:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 30,
        status: "Черновик",
        date: "2025-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 17,
        status: "Доставлено",
        date: "2025-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 18,
        status: "Оплачено",
        date: "2025-01-11:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 19,
        status: "Отправлен",
        date: "2025-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
    {
        id: 20,
        status: "Черновик",
        date: "2023-01-01:00:00",
        total: 1000,
        price: 1000,
        delivery: 100,
        declaration_number: "1234567890",
        tel: "+38 (099) 123-45-67",
        deliveyId: "234234234",
        address: "Днепр (Днепропетровская область, Поштомат Новая Почта №78900, проспект Свободы 21 (маг.АТБ)",
        city: "Днепр",
        products: [
            {
                id: 1,
                name: "Онлайн ИПБ ARIENT",
                price: 1000,
                quantity: 2,
                photo: moduleImg,
                description: "Однофазние ИБП",
            },
        ],
    },
]